global:
  project: "HuMob-Challenge-2023"
  seed: 8823
  resources: "/workspace/resources"
cycle:
  name: cycle_001
  task_dataset: "task2_dataset"
  group_keys: ["uid", "weekend", "t"]
  agg_method: "median"
  cycle_groups: [["uid", "t"]]
  T: 4
  eval:
    eval_uid_num: 1000
  inference:
    batch_size: 500
